### OUTPEER data science. Yernar Tolegenov

In [18]:
from random import seed
import numpy as np

np.random.seed(2024)

Y = np.random.rand(20, 1)
X = np.random.rand(20, 5)


print("Matrix Y:\n", Y)
print("\nMatrix X:\n", X)

def gradients(coef_3, coef_5, X, Y):
    x3 = X[:, 2]
    x5 = X[:, 4]
    preds_Y = coef_3 * x3 + coef_5 * x5
    differ = preds_Y - Y.ravel() #difference between predicted and actual values
    grad_3 = 2 * np.mean(differ * x3)
    grad_5 = 2 * np.mean(differ * x5)
    return grad_3, grad_5

def gradient_descent(X, Y, learning_rate=0.00001, iterations=10000):
    coef_3, coef_5 = 1.0, 1.0
    for _ in range(iterations):
        grad3, grad5 = gradients(coef_3, coef_5, X, Y)
        coef_3 -= learning_rate * grad3
        coef_5 -= learning_rate * grad5
    return coef_3, coef_5

coef3, coef5 = gradient_descent(X, Y)

def calculate_rmse(coef_3, coef_5, X, Y):
    x3 = X[:, 2]
    x5 = X[:, 4]
    preds_Y = coef_3 * x3 + coef_5 * x5
    rmse = np.sqrt(np.mean((preds_Y - Y.ravel()) ** 2))
    return rmse

rmse = calculate_rmse(coef3, coef5, X, Y)

results = [[coef3, coef5], rmse]
print('\n\nresults: ', results)

Matrix Y:
 [[0.58801452]
 [0.69910875]
 [0.18815196]
 [0.04380856]
 [0.20501895]
 [0.10606287]
 [0.72724014]
 [0.67940052]
 [0.4738457 ]
 [0.44829582]
 [0.01910695]
 [0.75259834]
 [0.60244854]
 [0.96177758]
 [0.66436865]
 [0.60662962]
 [0.44915131]
 [0.22535416]
 [0.6701743 ]
 [0.73576659]]

Matrix X:
 [[0.25799564 0.09554215 0.96090974 0.25176729 0.28216512]
 [0.76825393 0.7979234  0.5440372  0.38270763 0.38165095]
 [0.28582739 0.74026815 0.23898683 0.4377217  0.8835387 ]
 [0.28928114 0.78450686 0.75895366 0.41778538 0.22576877]
 [0.42009814 0.06436369 0.59643269 0.83732372 0.89248639]
 [0.20052744 0.50239523 0.89538184 0.25592093 0.86723234]
 [0.01648793 0.55249695 0.52790539 0.92335039 0.24594844]
 [0.06401838 0.9021047  0.8740398  0.16366729 0.99974131]
 [0.34680397 0.31287816 0.84710402 0.8802311  0.67655865]
 [0.05367515 0.55921377 0.69451294 0.8241973  0.31142866]
 [0.50523054 0.84900379 0.29351563 0.67711955 0.4209064 ]
 [0.68171271 0.22122799 0.5489977  0.84884672 0.7365669 ]
